#!/usr/bin/env zsh
emulate -L zsh -o extendedglob

local p=$1
[[ $1 == -p ]]&&shift
# Allow but strip non-number format codes, for future expansions
if ((!$+Options[-q])) || [[ -n $p ]]; then
    print -P "${${@//\{[^0-9][^\}]##\}/}//(#b)(\{[^\}]##\})/%F$match[1]}%f%b"
fi
